#! /bin/sh

if ! type pbcopy >/dev/null 2>&1 || ! type reattach-to-user-namespace >/dev/null 2>&1; then
  tmux display-message "Error: cannot copy to clipboard."
  exit 0
fi

tmux save-buffer ${HOME}/.tmux/local/tmp/.tmux-to-pbcopy
cat ${HOME}/.tmux/local/tmp/.tmux-to-pbcopy | pbcopy

# display messages 
HEAD=`head -1 ${HOME}/.tmux/local/tmp/.tmux_to_pbcopy`
TAIL=`tail -1 ${HOME}/.tmux/local/tmp/.tmux_to_pbcopy`
tmux display-message "Copy:  $HEAD  -  $TAIL"

#COPY=`tmux save-buffer -`
#echo "$COPY" | reattach-to-user-namespace pbcopy

# メッセージ表示
#LINES=`echo "$COPY" | wc -l | tr -d ' '`
#tmux display-message "Copy: $LINES lines"`'`

