#! /bin/sh

tmux save-buffer ~/.tmux.d/local/tmp/.tmux_to_pbcopy
cat ~/.tmux.d/local/tmp/.tmux_to_pbcopy | pbcopy

# display messages 
HEAD=`head -1 ~/.tmux.d/local/tmp/.tmux_to_pbcopy`
TAIL=`tail -1 ~/.tmux.d/local/tmp/.tmux_to_pbcopy`
tmux display-message "Copy:  $HEAD  -  $TAIL"

